theme: minima
url: "https://www.asazlab.com"
plugins:
  - jekyll-titles-from-headings
  - jekyll-sitemap
titles_from_headings:
  enabled:     true
  strip_title: true
  collections: false
twitter_username: BHInfoSecurity
github_username:  AntiSyphon
youtube_username: BlackHillsInformationSecurity
