
configuration AddUsers {
    param 
    ( 
        [Parameter(Mandatory)]
        [String]$DomainFQDN,

        [Parameter(Mandatory)]
        [System.Management.Automation.PSCredential]$AdminCreds

    ) 
    
    Import-DscResource -ModuleName ActiveDirectoryDsc, NetworkingDsc, xPSDesiredStateConfiguration, xDnsServer, ComputerManagementDsc
    
    [String] $DomainNetbiosName = (Get-NetBIOSName -DomainFQDN $DomainFQDN)
    [System.Management.Automation.PSCredential]$DomainCreds = New-Object System.Management.Automation.PSCredential ("${DomainNetbiosName}\$($Admincreds.UserName)", $Admincreds.Password)

    $Interface = Get-NetAdapter | Where-Object Name -Like "Ethernet*" | Select-Object -First 1
    $InterfaceAlias = $($Interface.Name)
    $bstr = [System.Runtime.InteropServices.Marshal]::SecureStringToBSTR($AdminCreds.Password)
    $AdminPassword = [System.Runtime.InteropServices.Marshal]::PtrToStringAuto($bstr)
    $ComputerName = Get-Content env:computername

    Node localhost
    {
        LocalConfigurationManager
        {           
            ConfigurationMode   = 'ApplyOnly'
            RebootNodeIfNeeded  = $true
        }

        # ***** Create Domain Users *****
        xScript CreateDomainUsers
        {
            SetScript = 
            {

             Write-Host "starting add users DSC"

                # Verifying ADWS service is running
                $ServiceName = 'ADWS'
                $arrService = Get-Service -Name $ServiceName

                while ($arrService.Status -ne 'Running')
                {
                    Start-Service $ServiceName
                    Start-Sleep -seconds 5
                    $arrService.Refresh()
                }

                Write-Host "creating new ous"

                try 
                {
                    New-ADOrganizationalUnit -Name "UserAccounts"
                    New-ADOrganizationalUnit -Name "ComputerAccounts"
                    New-ADOrganizationalUnit -Name "AdminAccounts"
                    New-ADOrganizationalUnit -Name "SecurityGroups" -Path "DC=asazlab,DC=com"
                    New-ADOrganizationalUnit -Name "SG_FileShares" -Path "OU=SecurityGroups,DC=asazlab,DC=com"
                    New-ADOrganizationalUnit -Name "ServiceAdmins" -Path "DC=asazlab,DC=com"
                }
                catch 
                {
                    Write-Host "error creating new ous"
                }

                Write-Host "adding new users"

                try 
                {               
                    DSADD user -upn itadmin@asazlab.com "cn=itadmin,ou=AdminAccounts,dc=asazlab,dc=com" -fn "it" -ln "admin" -disabled no -display "ITAdmin" -desc "Non-Destruct Medieval Architecture Specialist" -office "Administration" -title "Controller" -company "DevLabs" -PWD "ThisShouldBeLongerThan20"
                    Add-ADGroupMember -Identity "Domain Admins" -Members itadmin
                    DSADD user -upn Luis.Graves@asazlab.com "cn=Luis.Graves,ou=UserAccounts,dc=asazlab,dc=com" -fn "Luis" -ln "Graves" -disabled no -display "Luis Graves" -desc "Accounting Controller" -office "Accounting" -title "Controller" -company "DevLabs" -PWD "Badpass76918"
                    DSADD user -upn Pam.Sparks@asazlab.com "cn=Pam.Sparks,ou=UserAccounts,dc=asazlab,dc=com" -fn "Pam" -ln "Sparks" -disabled no -display "Pam Sparks" -desc "Accounting Accounts Payable" -office "DevLabs Accounting" -title "Accounts Payable" -company "DevLabs" -PWD "Badpass30886"
                    DSADD user -upn Jesus.Robertson@asazlab.com "cn=Jesus.Robertson,ou=UserAccounts,dc=asazlab,dc=com" -fn "Jesus" -ln "Robertson" -disabled no -display "Jesus Robertson" -desc "Accounting Accounts Receivable" -office "DevLabs Accounting" -title "Accounts Receivable" -company "DevLabs" -PWD "Badpass33835"
                    DSADD user -upn Nellie.Blair@asazlab.com "cn=Nellie.Blair,ou=UserAccounts,dc=asazlab,dc=com" -fn "Nellie" -ln "Blair" -disabled no -display "Nellie Blair" -desc "WholeSales Wholesale Sales" -office "DevLabs WholeSales" -title "Wholesale Sales" -company "DevLabs" -PWD "Badpass22601"
                    DSADD user -upn Carl.Pearson@asazlab.com "cn=Carl.Pearson,ou=UserAccounts,dc=asazlab,dc=com" -fn "Carl" -ln "Pearson" -disabled no -display "Carl Pearson" -desc "WholeSales Wholesale Sales" -office "DevLabs WholeSales" -title "Wholesale Sales" -company "DevLabs" -PWD "Badpass23644"
                    DSADD user -upn Geneva.Bryant@asazlab.com "cn=Geneva.Bryant,ou=UserAccounts,dc=asazlab,dc=com" -fn "Geneva" -ln "Bryant" -disabled no -display "Geneva Bryant" -desc "WholeSales Wholesale Sales" -office "DevLabs WholeSales" -title "Wholesale Sales" -company "DevLabs" -PWD "Badpass59456"
                    DSADD user -upn Diana.Henderson@asazlab.com "cn=Diana.Henderson,ou=UserAccounts,dc=asazlab,dc=com" -fn "Diana" -ln "Henderson" -disabled no -display "Diana Henderson" -desc "Transportation Logistics Manager" -office "DevLabs Transportaion" -title "Logistics Manager" -company "DevLabs" -PWD "Badpass82796"
                    DSADD user -upn Courtney.Mitchell@asazlab.com "cn=Courtney.Mitchell,ou=UserAccounts,dc=asazlab,dc=com" -fn "Courtney" -ln "Mitchell" -disabled no -display "Courtney Mitchell" -desc "Transportation Logistics Assistant" -office "DevLabs Transportation" -title "Logistics Assistant" -company "DevLabs" -PWD "Badpass77145"
                    DSADD user -upn Gina.Hampton@asazlab.com "cn=Gina.Hampton,ou=UserAccounts,dc=asazlab,dc=com" -fn "Gina" -ln "Hampton" -disabled no -display "Gina Hampton" -desc "Bakery Production Director of Bakering" -office "DevLabs Bakery Production" -title "Director of Bakering" -company "DevLabs" -PWD "Badpass94578"
                    DSADD user -upn Otis.Mullins@asazlab.com "cn=Otis.Mullins,ou=UserAccounts,dc=asazlab,dc=com" -fn "Otis" -ln "Mullins" -disabled no -display "Otis Mullins" -desc "Bakery Production Head Baker" -office "DevLabs Bakery Production" -title "Head Baker" -company "DevLabs" -PWD "Badpass46747"
                    DSADD user -upn Gordon.Phillips@asazlab.com "cn=Gordon.Phillips,ou=UserAccounts,dc=asazlab,dc=com" -fn "Gordon" -ln "Phillips" -disabled no -display "Gordon Phillips" -desc "Bakery Production Head Baker" -office "DevLabs Bakery Production" -title "Head Baker" -company "DevLabs" -PWD "Badpass59314"
                    DSADD user -upn Olive.Ross@asazlab.com "cn=Olive.Ross,ou=UserAccounts,dc=asazlab,dc=com" -fn "Olive" -ln "Ross" -disabled no -display "Olive Ross" -desc "Bakery Production Baker" -office "DevLabs Bakery Production" -title "Baker" -company "DevLabs" -PWD "Badpass23913"
                    DSADD user -upn Roxanne.Greer@asazlab.com "cn=Roxanne.Greer,ou=UserAccounts,dc=asazlab,dc=com" -fn "Roxanne" -ln "Greer" -disabled no -display "Roxanne Greer" -desc "Bakery Production Baker" -office "DevLabs Bakery Production" -title "Baker" -company "DevLabs" -PWD "Badpass65009"
                    DSADD user -upn Willie.Herrera@asazlab.com "cn=Willie.Herrera,ou=UserAccounts,dc=asazlab,dc=com" -fn "Willie" -ln "Herrera" -disabled no -display "Willie Herrera" -desc "Bakery Production Baker" -office "DevLabs Bakery Production" -title "Baker" -company "DevLabs" -PWD "Badpass89503"
                    DSADD user -upn Randal.Simpson@asazlab.com "cn=Randal.Simpson,ou=UserAccounts,dc=asazlab,dc=com" -fn "Randal" -ln "Simpson" -disabled no -display "Randal Simpson" -desc "Bakery Production Baker" -office "DevLabs Bakery Production" -title "Baker" -company "DevLabs" -PWD "Badpass32673"
                    DSADD user -upn Bradley.Christensen@asazlab.com "cn=Bradley.Christensen,ou=UserAccounts,dc=asazlab,dc=com" -fn "Bradley" -ln "Christensen" -disabled no -display "Bradley Christensen" -desc "Bakery Production Baker" -office "DevLabs Bakery Production" -title "Baker" -company "DevLabs" -PWD "Badpass67659"
                    DSADD user -upn Heather.Butler@asazlab.com "cn=Heather.Butler,ou=UserAccounts,dc=asazlab,dc=com" -fn "Heather" -ln "Butler" -disabled no -display "Heather Butler" -desc "Bakery Production Purchasing Agent" -office "DevLabs Bakery Production" -title "Purchasing Agent" -company "DevLabs" -PWD "Badpass25808"
                    DSADD user -upn Elisa.Lawson@asazlab.com "cn=Elisa.Lawson,ou=UserAccounts,dc=asazlab,dc=com" -fn "Elisa" -ln "Lawson" -disabled no -display "Elisa Lawson" -desc "Bakery Production Confectionary Specialist" -office "DevLabs Bakery Production" -title "Confectionary Specialist" -company "DevLabs" -PWD "Badpass93896"
                    DSADD user -upn Kristi.Silva@asazlab.com "cn=Kristi.Silva,ou=UserAccounts,dc=asazlab,dc=com" -fn "Kristi" -ln "Silva" -disabled no -display "Kristi Silva" -desc "Bakery Production Confectionary Specialist" -office "DevLabs Bakery Production" -title "Confectionary Specialist" -company "DevLabs" -PWD "Badpass66729"
                    DSADD user -upn Ed.Barnes@asazlab.com "cn=Ed.Barnes,ou=UserAccounts,dc=asazlab,dc=com" -fn "Ed" -ln "Barnes" -disabled no -display "Ed Barnes" -desc "BusAdmin Office Manager" -office "DevLabs BusAdmin" -title "Office Manager" -company "DevLabs" -PWD "Badpass21561"
                    DSADD user -upn Angela.Garner@asazlab.com "cn=Angela.Garner,ou=UserAccounts,dc=asazlab,dc=com" -fn "Angela" -ln "Garner" -disabled no -display "Angela Garner" -desc "Facilities Facilities Manager" -office "DevLabs Facilities" -title "Facilities Manager" -company "DevLabs" -PWD "Badpass77813"
                    DSADD user -upn Lynda.Bowman@asazlab.com "cn=Lynda.Bowman,ou=UserAccounts,dc=asazlab,dc=com" -fn "Lynda" -ln "Bowman" -disabled no -display "Lynda Bowman" -desc "IT Systems Support" -office "DevLabs IT" -title "Systems Support" -company "DevLabs" -PWD "Badpass28487"
                    DSADD user -upn Kathleen.Delgado@asazlab.com "cn=Kathleen.Delgado,ou=UserAccounts,dc=asazlab,dc=com" -fn "Kathleen" -ln "Delgado" -disabled no -display "Kathleen Delgado" -desc "IT WebDev Marketer" -office "DevLabs IT" -title "WebDev Marketer" -company "DevLabs" -PWD "Badpass97825"
                    DSADD user -upn Eileen.Moss@asazlab.com "cn=Eileen.Moss,ou=UserAccounts,dc=asazlab,dc=com" -fn "Eileen" -ln "Moss" -disabled no -display "Eileen Moss" -desc "BusAdmin Owner" -office "DevLabs BusAdmin" -title "Owner" -company "DevLabs" -PWD "Badpass51776"
                    DSADD user -upn IT.Admin@asazlab.com "cn=IT.Admin,ou=UserAccounts,dc=asazlab,dc=com" -fn "IT" -ln "Admin" -disabled no -display "IT Admin" -desc "IT DEPARTMENT IT SUPERUSER ACCOUNT" -office "DevLabs IT DEPARTMENT" -title "IT SUPERUSER ACCOUNT" -company "DevLabs" -PWD "Badpass99999"
                    DSADD user -upn Josefina.Robbins@asazlab.com "cn=Josefina.Robbins,ou=UserAccounts,dc=asazlab,dc=com" -fn "Josefina" -ln "Robbins" -disabled no -display "Josefina Robbins" -desc "Testing Grounds Of Intervening Epeirogenics Medical Physics Professor" -office "DevLabs Testing Grounds Of Intervening Epeirogenics" -title "Medical Physics Professor" -company "DevLabs" -PWD "Badpass39351"
                    DSADD user -upn Toni.Spencer@asazlab.com "cn=Toni.Spencer,ou=UserAccounts,dc=asazlab,dc=com" -fn "Toni" -ln "Spencer" -disabled no -display "Toni Spencer" -desc "Testing Grounds Of Intervening Epeirogenics Sterilization Technician" -office "DevLabs Testing Grounds Of Intervening Epeirogenics" -title "Sterilization Technician" -company "DevLabs" -PWD "Badpass75041"
                    DSADD user -upn Becky.Wise@asazlab.com "cn=Becky.Wise,ou=UserAccounts,dc=asazlab,dc=com" -fn "Becky" -ln "Wise" -disabled no -display "Becky Wise" -desc "Testing Grounds Of Intervening Epeirogenics Honest John Rocket Crew Member" -office "DevLabs Testing Grounds Of Intervening Epeirogenics" -title "Honest John Rocket Crew Member" -company "DevLabs" -PWD "Badpass55039"
                    DSADD user -upn Vicky.Hansen@asazlab.com "cn=Vicky.Hansen,ou=UserAccounts,dc=asazlab,dc=com" -fn "Vicky" -ln "Hansen" -disabled no -display "Vicky Hansen" -desc "Testing Grounds Of Intervening Epeirogenics PBX Operator" -office "DevLabs Testing Grounds Of Intervening Epeirogenics" -title "PBX Operator" -company "DevLabs" -PWD "Badpass1834"
                    DSADD user -upn Juana.Fitzgerald@asazlab.com "cn=Juana.Fitzgerald,ou=UserAccounts,dc=asazlab,dc=com" -fn "Juana" -ln "Fitzgerald" -disabled no -display "Juana Fitzgerald" -desc "Testing Grounds Of Intervening Epeirogenics Field Map Technician" -office "DevLabs Testing Grounds Of Intervening Epeirogenics" -title "Field Map Technician" -company "DevLabs" -PWD "Badpass18832"
                    DSADD user -upn Judith.Green@asazlab.com "cn=Judith.Green,ou=UserAccounts,dc=asazlab,dc=com" -fn "Judith" -ln "Green" -disabled no -display "Judith Green" -desc "Testing Grounds Of Intervening Epeirogenics Combine Mechanic" -office "DevLabs Testing Grounds Of Intervening Epeirogenics" -title "Combine Mechanic" -company "DevLabs" -PWD "Badpass91238"
                    DSADD user -upn Drew.Simmons@asazlab.com "cn=Drew.Simmons,ou=UserAccounts,dc=asazlab,dc=com" -fn "Drew" -ln "Simmons" -disabled no -display "Drew Simmons" -desc "Testing Grounds Of Intervening Epeirogenics School Bus Driver" -office "DevLabs Testing Grounds Of Intervening Epeirogenics" -title "School Bus Driver" -company "DevLabs" -PWD "Badpass53349"
                    DSADD user -upn Ernestine.Blake@asazlab.com "cn=Ernestine.Blake,ou=UserAccounts,dc=asazlab,dc=com" -fn "Ernestine" -ln "Blake" -disabled no -display "Ernestine Blake" -desc "Testing Grounds Of Intervening Epeirogenics Merchandise Displayer" -office "DevLabs Testing Grounds Of Intervening Epeirogenics" -title "Merchandise Displayer" -company "DevLabs" -PWD "Badpass12790"
                    DSADD user -upn Vickie.Ray@asazlab.com "cn=Vickie.Ray,ou=UserAccounts,dc=asazlab,dc=com" -fn "Vickie" -ln "Ray" -disabled no -display "Vickie Ray" -desc "Testing Grounds Of Intervening Epeirogenics National Association for Stock Car Auto Racing Driver" -office "DevLabs Testing Grounds Of Intervening Epeirogenics" -title "National Association for Stock Car Auto Racing Driver" -company "DevLabs" -PWD "Badpass62326"
                    DSADD user -upn Jerry.Lawrence@asazlab.com "cn=Jerry.Lawrence,ou=UserAccounts,dc=asazlab,dc=com" -fn "Jerry" -ln "Lawrence" -disabled no -display "Jerry Lawrence" -desc "Test Center Of The Analysis Of Florigenics Independent Insurance Adjuster" -office "DevLabs Test Center Of The Analysis Of Florigenics" -title "Independent Insurance Adjuster" -company "DevLabs" -PWD "Badpass55938"
                    DSADD user -upn Darlene.Gibbs@asazlab.com "cn=Darlene.Gibbs,ou=UserAccounts,dc=asazlab,dc=com" -fn "Darlene" -ln "Gibbs" -disabled no -display "Darlene Gibbs" -desc "Test Center Of The Analysis Of Florigenics Electronic Warfare Specialist" -office "DevLabs Test Center Of The Analysis Of Florigenics" -title "Electronic Warfare Specialist" -company "DevLabs" -PWD "Badpass46644"
                    DSADD user -upn Jeremy.Willis@asazlab.com "cn=Jeremy.Willis,ou=UserAccounts,dc=asazlab,dc=com" -fn "Jeremy" -ln "Willis" -disabled no -display "Jeremy Willis" -desc "Test Center Of The Analysis Of Florigenics Administrative Court Justice" -office "DevLabs Test Center Of The Analysis Of Florigenics" -title "Administrative Court Justice" -company "DevLabs" -PWD "Badpass86499"
                    DSADD user -upn Kathy.Montgomery@asazlab.com "cn=Kathy.Montgomery,ou=UserAccounts,dc=asazlab,dc=com" -fn "Kathy" -ln "Montgomery" -disabled no -display "Kathy Montgomery" -desc "Test Center Of The Analysis Of Florigenics Prescription Clerk" -office "DevLabs Test Center Of The Analysis Of Florigenics" -title "Prescription Clerk" -company "DevLabs" -PWD "Badpass89450"
                    DSADD user -upn Veronica.Sparks@asazlab.com "cn=Veronica.Sparks,ou=UserAccounts,dc=asazlab,dc=com" -fn "Veronica" -ln "Sparks" -disabled no -display "Veronica Sparks" -desc "Test Center Of The Analysis Of Florigenics Guided Missile Launching System Maintenance Technician" -office "DevLabs Test Center Of The Analysis Of Florigenics" -title "Guided Missile Launching System Maintenance Technician" -company "DevLabs" -PWD "Badpass22385"
                    DSADD user -upn Bertha.Schultz@asazlab.com "cn=Bertha.Schultz,ou=UserAccounts,dc=asazlab,dc=com" -fn "Bertha" -ln "Schultz" -disabled no -display "Bertha Schultz" -desc "Test Center Of The Analysis Of Florigenics Staff Air Defense Officer" -office "DevLabs Test Center Of The Analysis Of Florigenics" -title "Staff Air Defense Officer" -company "DevLabs" -PWD "Badpass90332"
                    DSADD user -upn Judy.Bowen@asazlab.com "cn=Judy.Bowen,ou=UserAccounts,dc=asazlab,dc=com" -fn "Judy" -ln "Bowen" -disabled no -display "Judy Bowen" -desc "Test Center Of The Analysis Of Florigenics Film Process Operator" -office "DevLabs Test Center Of The Analysis Of Florigenics" -title "Film Process Operator" -company "DevLabs" -PWD "Badpass76659"
                    DSADD user -upn Candace.Martinez@asazlab.com "cn=Candace.Martinez,ou=UserAccounts,dc=asazlab,dc=com" -fn "Candace" -ln "Martinez" -disabled no -display "Candace Martinez" -desc "Test Center Of The Analysis Of Florigenics Aircraft Loadmaster Superintendent" -office "DevLabs Test Center Of The Analysis Of Florigenics" -title "Aircraft Loadmaster Superintendent" -company "DevLabs" -PWD "Badpass83152"
                    DSADD user -upn Everett.Watkins@asazlab.com "cn=Everett.Watkins,ou=UserAccounts,dc=asazlab,dc=com" -fn "Everett" -ln "Watkins" -disabled no -display "Everett Watkins" -desc "Defense Lab Of Obscure Transgenics Lay Health Advocate" -office "DevLabs Defense Lab Of Obscure Transgenics" -title "Lay Health Advocate" -company "DevLabs" -PWD "Badpass16102"
                    DSADD user -upn Mandy.Rhodes@asazlab.com "cn=Mandy.Rhodes,ou=UserAccounts,dc=asazlab,dc=com" -fn "Mandy" -ln "Rhodes" -disabled no -display "Mandy Rhodes" -desc "Test Center Of Declined Ergogenics Geophysical Manager" -office "DevLabs Test Center Of Declined Ergogenics" -title "Geophysical Manager" -company "DevLabs" -PWD "Badpass31055"
                    DSADD user -upn Gail.Kennedy@asazlab.com "cn=Gail.Kennedy,ou=UserAccounts,dc=asazlab,dc=com" -fn "Gail" -ln "Kennedy" -disabled no -display "Gail Kennedy" -desc "Defense Lab Of Obscure Transgenics Ship's Electronic Warfare Officer" -office "DevLabs Defense Lab Of Obscure Transgenics" -title "Ship's Electronic Warfare Officer" -company "DevLabs" -PWD "Badpass60705"
                    DSADD user -upn Elmer.Wagner@asazlab.com "cn=Elmer.Wagner,ou=UserAccounts,dc=asazlab,dc=com" -fn "Elmer" -ln "Wagner" -disabled no -display "Elmer Wagner" -desc "Test Center Of Declined Ergogenics MIS Director" -office "DevLabs Test Center Of Declined Ergogenics" -title "MIS Director" -company "DevLabs" -PWD "Badpass7611"
                    DSADD user -upn Angela.Hampton@asazlab.com "cn=Angela.Hampton,ou=UserAccounts,dc=asazlab,dc=com" -fn "Angela" -ln "Hampton" -disabled no -display "Angela Hampton" -desc "Defense Lab Of Obscure Transgenics Peer Health Promoter" -office "DevLabs Defense Lab Of Obscure Transgenics" -title "Peer Health Promoter" -company "DevLabs" -PWD "Badpass60044"
                    DSADD user -upn Claire.Munoz@asazlab.com "cn=Claire.Munoz,ou=UserAccounts,dc=asazlab,dc=com" -fn "Claire" -ln "Munoz" -disabled no -display "Claire Munoz" -desc "Test Center Of Declined Ergogenics Secondary School Principal" -office "DevLabs Test Center Of Declined Ergogenics" -title "Secondary School Principal" -company "DevLabs" -PWD "Badpass11608"
                    DSADD user -upn Joanna.Patton@asazlab.com "cn=Joanna.Patton,ou=UserAccounts,dc=asazlab,dc=com" -fn "Joanna" -ln "Patton" -disabled no -display "Joanna Patton" -desc "Defense Lab Of Obscure Transgenics Banquet Manager" -office "DevLabs Defense Lab Of Obscure Transgenics" -title "Banquet Manager" -company "DevLabs" -PWD "Badpass59451"
                    DSADD user -upn Elaine.Carson@asazlab.com "cn=Elaine.Carson,ou=UserAccounts,dc=asazlab,dc=com" -fn "Elaine" -ln "Carson" -disabled no -display "Elaine Carson" -desc "Test Center Of Declined Ergogenics Service Forester" -office "DevLabs Test Center Of Declined Ergogenics" -title "Service Forester" -company "DevLabs" -PWD "Badpass30285"
                    DSADD user -upn Shelia.Osborne@asazlab.com "cn=Shelia.Osborne,ou=UserAccounts,dc=asazlab,dc=com" -fn "Shelia" -ln "Osborne" -disabled no -display "Shelia Osborne" -desc "Defense Lab Of Obscure Transgenics Computer Security Specialist" -office "DevLabs Defense Lab Of Obscure Transgenics" -title "Computer Security Specialist" -company "DevLabs" -PWD "Badpass46566"
                    DSADD user -upn Alberto.Patterson@asazlab.com "cn=Alberto.Patterson,ou=UserAccounts,dc=asazlab,dc=com" -fn "Alberto" -ln "Patterson" -disabled no -display "Alberto Patterson" -desc "Test Center Of Declined Ergogenics Computer Systems Security Analyst" -office "DevLabs Test Center Of Declined Ergogenics" -title "Computer Systems Security Analyst" -company "DevLabs" -PWD "Badpass31258"
                    DSADD user -upn Bonnie.Barber@asazlab.com "cn=Bonnie.Barber,ou=UserAccounts,dc=asazlab,dc=com" -fn "Bonnie" -ln "Barber" -disabled no -display "Bonnie Barber" -desc "Defense Lab Of Obscure Transgenics Information Security Analyst" -office "DevLabs Defense Lab Of Obscure Transgenics" -title "Information Security Analyst" -company "DevLabs" -PWD "Badpass8383"
                    DSADD user -upn Christian.Frazier@asazlab.com "cn=Christian.Frazier,ou=UserAccounts,dc=asazlab,dc=com" -fn "Christian" -ln "Frazier" -disabled no -display "Christian Frazier" -desc "Test Center Of Declined Ergogenics Information Systems Security Analyst" -office "DevLabs Test Center Of Declined Ergogenics" -title "Information Systems Security Analyst" -company "DevLabs" -PWD "Badpass85995"
                    DSADD user -upn Cheryl.Ford@asazlab.com "cn=Cheryl.Ford,ou=UserAccounts,dc=asazlab,dc=com" -fn "Cheryl" -ln "Ford" -disabled no -display "Cheryl Ford" -desc "Test Center Of The Deterioration Of Palynology Internet Security Specialist" -office "DevLabs Test Center Of The Deterioration Of Palynology" -title "Internet Security Specialist" -company "DevLabs" -PWD "Badpass42850"
                    DSADD user -upn Leslie.Francis@asazlab.com "cn=Leslie.Francis,ou=UserAccounts,dc=asazlab,dc=com" -fn "Leslie" -ln "Francis" -disabled no -display "Leslie Francis" -desc "Test Center Of The Deterioration Of Palynology Network Security Analyst" -office "DevLabs Test Center Of The Deterioration Of Palynology" -title "Network Security Analyst" -company "DevLabs" -PWD "Badpass79876"
                    DSADD user -upn Dwight.Burns@asazlab.com "cn=Dwight.Burns,ou=UserAccounts,dc=asazlab,dc=com" -fn "Dwight" -ln "Burns" -disabled no -display "Dwight Burns" -desc "Test Center Of The Deterioration Of Palynology Applications Programmer" -office "DevLabs Test Center Of The Deterioration Of Palynology" -title "Applications Programmer" -company "DevLabs" -PWD "Badpass46592"
                    DSADD user -upn Jill.Roberts@asazlab.com "cn=Jill.Roberts,ou=UserAccounts,dc=asazlab,dc=com" -fn "Jill" -ln "Roberts" -disabled no -display "Jill Roberts" -desc "Test Center Of The Deterioration Of Palynology Computer Language Coder" -office "DevLabs Test Center Of The Deterioration Of Palynology" -title "Computer Language Coder" -company "DevLabs" -PWD "Badpass57759"
                    DSADD user -upn Tamara.Armstrong@asazlab.com "cn=Tamara.Armstrong,ou=UserAccounts,dc=asazlab,dc=com" -fn "Tamara" -ln "Armstrong" -disabled no -display "Tamara Armstrong" -desc "Test Center Of The Deterioration Of Palynology Computer Programmer" -office "DevLabs Test Center Of The Deterioration Of Palynology" -title "Computer Programmer" -company "DevLabs" -PWD "Badpass32165"
                    DSADD user -upn Lionel.Vaughn@asazlab.com "cn=Lionel.Vaughn,ou=UserAccounts,dc=asazlab,dc=com" -fn "Lionel" -ln "Vaughn" -disabled no -display "Lionel Vaughn" -desc "Test Center Of The Deterioration Of Palynology Junior Software Developer" -office "DevLabs Test Center Of The Deterioration Of Palynology" -title "Junior Software Developer" -company "DevLabs" -PWD "Badpass65184"
                    DSADD user -upn Carmen.Chambers@asazlab.com "cn=Carmen.Chambers,ou=UserAccounts,dc=asazlab,dc=com" -fn "Carmen" -ln "Chambers" -disabled no -display "Carmen Chambers" -desc "Test Center Of The Deterioration Of Palynology Mainframe Programmer" -office "DevLabs Test Center Of The Deterioration Of Palynology" -title "Mainframe Programmer" -company "DevLabs" -PWD "Badpass31637"
                    DSADD user -upn Taylor.Gill@asazlab.com "cn=Taylor.Gill,ou=UserAccounts,dc=asazlab,dc=com" -fn "Taylor" -ln "Gill" -disabled no -display "Taylor Gill" -desc "Test Center Of The Deterioration Of Palynology Systems Programmer" -office "DevLabs Test Center Of The Deterioration Of Palynology" -title "Systems Programmer" -company "DevLabs" -PWD "Badpass39026"
                    DSADD user -upn Cora.Bowman@asazlab.com "cn=Cora.Bowman,ou=UserAccounts,dc=asazlab,dc=com" -fn "Cora" -ln "Bowman" -disabled no -display "Cora Bowman" -desc "Test Center Of The Deterioration Of Palynology Application Integration Engineer" -office "DevLabs Test Center Of The Deterioration Of Palynology" -title "Application Integration Engineer" -company "DevLabs" -PWD "Badpass87180"
                    DSADD user -upn Virginia.Adkins@asazlab.com "cn=Virginia.Adkins,ou=UserAccounts,dc=asazlab,dc=com" -fn "Virginia" -ln "Adkins" -disabled no -display "Virginia Adkins" -desc "Test Center Of The Deterioration Of Palynology Applications Developer" -office "DevLabs Test Center Of The Deterioration Of Palynology" -title "Applications Developer" -company "DevLabs" -PWD "Badpass56388"
                    DSADD user -upn Jody.Haynes@asazlab.com "cn=Jody.Haynes,ou=UserAccounts,dc=asazlab,dc=com" -fn "Jody" -ln "Haynes" -disabled no -display "Jody Haynes" -desc "Research Lab Of Mutating Garbology Computer Applications Developer" -office "DevLabs Research Lab Of Mutating Garbology" -title "Computer Applications Developer" -company "DevLabs" -PWD "Badpass59005"
                    DSADD user -upn Corey.Quinn@asazlab.com "cn=Corey.Quinn,ou=UserAccounts,dc=asazlab,dc=com" -fn "Corey" -ln "Quinn" -disabled no -display "Corey Quinn" -desc "Research Lab Of Mutating Garbology Computer Applications Engineer" -office "DevLabs Research Lab Of Mutating Garbology" -title "Computer Applications Engineer" -company "DevLabs" -PWD "Badpass85030"
                    DSADD user -upn Nancy.Yates@asazlab.com "cn=Nancy.Yates,ou=UserAccounts,dc=asazlab,dc=com" -fn "Nancy" -ln "Yates" -disabled no -display "Nancy Yates" -desc "Research Lab Of Mutating Garbology Database Developer" -office "DevLabs Research Lab Of Mutating Garbology" -title "Database Developer" -company "DevLabs" -PWD "Badpass43517"
                    DSADD user -upn Eleanor.Olson@asazlab.com "cn=Eleanor.Olson,ou=UserAccounts,dc=asazlab,dc=com" -fn "Eleanor" -ln "Olson" -disabled no -display "Eleanor Olson" -desc "Research Lab Of Mutating Garbology Software Applications Architect" -office "DevLabs Research Lab Of Mutating Garbology" -title "Software Applications Architect" -company "DevLabs" -PWD "Badpass74648"
                    DSADD user -upn Shari.Hunt@asazlab.com "cn=Shari.Hunt,ou=UserAccounts,dc=asazlab,dc=com" -fn "Shari" -ln "Hunt" -disabled no -display "Shari Hunt" -desc "Research Lab Of Mutating Garbology Software Applications Designer" -office "DevLabs Research Lab Of Mutating Garbology" -title "Software Applications Designer" -company "DevLabs" -PWD "Badpass63423"
                    DSADD user -upn Willie.Gonzales@asazlab.com "cn=Willie.Gonzales,ou=UserAccounts,dc=asazlab,dc=com" -fn "Willie" -ln "Gonzales" -disabled no -display "Willie Gonzales" -desc "Research Lab Of Mutating Garbology Software Applications Engineer" -office "DevLabs Research Lab Of Mutating Garbology" -title "Software Applications Engineer" -company "DevLabs" -PWD "Badpass57169"
                    DSADD user -upn Rickey.Campbell@asazlab.com "cn=Rickey.Campbell,ou=UserAccounts,dc=asazlab,dc=com" -fn "Rickey" -ln "Campbell" -disabled no -display "Rickey Campbell" -desc "Research Lab Of Mutating Garbology Actuarial Associate" -office "DevLabs Research Lab Of Mutating Garbology" -title "Actuarial Associate" -company "DevLabs" -PWD "Badpass91838"
                    DSADD user -upn Pablo.Goodman@asazlab.com "cn=Pablo.Goodman,ou=UserAccounts,dc=asazlab,dc=com" -fn "Pablo" -ln "Goodman" -disabled no -display "Pablo Goodman" -desc "Research Lab Of Mutating Garbology Actuarial Mathematician" -office "DevLabs Research Lab Of Mutating Garbology" -title "Actuarial Mathematician" -company "DevLabs" -PWD "Badpass71031"
                    DSADD user -upn Maureen.Rios@asazlab.com "cn=Maureen.Rios,ou=UserAccounts,dc=asazlab,dc=com" -fn "Maureen" -ln "Rios" -disabled no -display "Maureen Rios" -desc "Defense Lab Of The Rectification Of Dysgenics Health Actuary" -office "DevLabs Defense Lab Of The Rectification Of Dysgenics" -title "Health Actuary" -company "DevLabs" -PWD "Badpass5877"
                    DSADD user -upn Jim.Bailey@asazlab.com "cn=Jim.Bailey,ou=UserAccounts,dc=asazlab,dc=com" -fn "Jim" -ln "Bailey" -disabled no -display "Jim Bailey" -desc "Defense Lab Of The Rectification Of Dysgenics Insurance Actuary" -office "DevLabs Defense Lab Of The Rectification Of Dysgenics" -title "Insurance Actuary" -company "DevLabs" -PWD "Badpass13637"
                    DSADD user -upn Debbie.Harrison@asazlab.com "cn=Debbie.Harrison,ou=UserAccounts,dc=asazlab,dc=com" -fn "Debbie" -ln "Harrison" -disabled no -display "Debbie Harrison" -desc "Defense Lab Of The Rectification Of Dysgenics Pricing Actuary" -office "DevLabs Defense Lab Of The Rectification Of Dysgenics" -title "Pricing Actuary" -company "DevLabs" -PWD "Badpass34971"
                    DSADD user -upn Timmy.Richardson@asazlab.com "cn=Timmy.Richardson,ou=UserAccounts,dc=asazlab,dc=com" -fn "Timmy" -ln "Richardson" -disabled no -display "Timmy Richardson" -desc "Defense Lab Of The Rectification Of Dysgenics Product Development Actuary" -office "DevLabs Defense Lab Of The Rectification Of Dysgenics" -title "Product Development Actuary" -company "DevLabs" -PWD "Badpass46037"
                    DSADD user -upn Samantha.Ryan@asazlab.com "cn=Samantha.Ryan,ou=UserAccounts,dc=asazlab,dc=com" -fn "Samantha" -ln "Ryan" -disabled no -display "Samantha Ryan" -desc "Defense Lab Of The Rectification Of Dysgenics Operations Analyst" -office "DevLabs Defense Lab Of The Rectification Of Dysgenics" -title "Operations Analyst" -company "DevLabs" -PWD "Badpass5033"
                    DSADD user -upn Roderick.Stone@asazlab.com "cn=Roderick.Stone,ou=UserAccounts,dc=asazlab,dc=com" -fn "Roderick" -ln "Stone" -disabled no -display "Roderick Stone" -desc "Defense Lab Of The Rectification Of Dysgenics Operations Research Analyst" -office "DevLabs Defense Lab Of The Rectification Of Dysgenics" -title "Operations Research Analyst" -company "DevLabs" -PWD "Badpass1984"
                    DSADD user -upn Jackie.Hall@asazlab.com "cn=Jackie.Hall,ou=UserAccounts,dc=asazlab,dc=com" -fn "Jackie" -ln "Hall" -disabled no -display "Jackie Hall" -desc "Defense Lab Of The Rectification Of Dysgenics Procedure Analyst" -office "DevLabs Defense Lab Of The Rectification Of Dysgenics" -title "Procedure Analyst" -company "DevLabs" -PWD "Badpass62950"
                    DSADD user -upn Sylvia.Mcgee@asazlab.com "cn=Sylvia.Mcgee,ou=UserAccounts,dc=asazlab,dc=com" -fn "Sylvia" -ln "Mcgee" -disabled no -display "Sylvia Mcgee" -desc "Defense Lab Of The Rectification Of Dysgenics Process Analyst" -office "DevLabs Defense Lab Of The Rectification Of Dysgenics" -title "Process Analyst" -company "DevLabs" -PWD "Badpass81222"
                    DSADD user -upn Bernice.Lawson@asazlab.com "cn=Bernice.Lawson,ou=UserAccounts,dc=asazlab,dc=com" -fn "Bernice" -ln "Lawson" -disabled no -display "Bernice Lawson" -desc "Defense Lab Of The Rectification Of Dysgenics Animal Breeder" -office "DevLabs Defense Lab Of The Rectification Of Dysgenics" -title "Animal Breeder" -company "DevLabs" -PWD "Badpass54618"
                    DSADD user -upn Kyle.Owen@asazlab.com "cn=Kyle.Owen,ou=UserAccounts,dc=asazlab,dc=com" -fn "Kyle" -ln "Owen" -disabled no -display "Kyle Owen" -desc "Defense Lab Of The Rectification Of Dysgenics Cat Breeder" -office "DevLabs Defense Lab Of The Rectification Of Dysgenics" -title "Cat Breeder" -company "DevLabs" -PWD "Badpass64815"
                    DSADD user -upn Orlando.Bennett@asazlab.com "cn=Orlando.Bennett,ou=UserAccounts,dc=asazlab,dc=com" -fn "Orlando" -ln "Bennett" -disabled no -display "Orlando Bennett" -desc "Defense Lab Of The Rectification Of Dysgenics Dairy Husbandry Worker" -office "DevLabs Defense Lab Of The Rectification Of Dysgenics" -title "Dairy Husbandry Worker" -company "DevLabs" -PWD "Badpass83275"
                    DSADD user -upn Cindy.Vargas@asazlab.com "cn=Cindy.Vargas,ou=UserAccounts,dc=asazlab,dc=com" -fn "Cindy" -ln "Vargas" -disabled no -display "Cindy Vargas" -desc "Defense Lab Of The Rectification Of Dysgenics Dog Breeder" -office "DevLabs Defense Lab Of The Rectification Of Dysgenics" -title "Dog Breeder" -company "DevLabs" -PWD "Badpass73142"
                    DSADD user -upn Geneva.Murphy@asazlab.com "cn=Geneva.Murphy,ou=UserAccounts,dc=asazlab,dc=com" -fn "Geneva" -ln "Murphy" -disabled no -display "Geneva Murphy" -desc "Defense Lab Of The Rectification Of Dysgenics Equine Breeder" -office "DevLabs Defense Lab Of The Rectification Of Dysgenics" -title "Equine Breeder" -company "DevLabs" -PWD "Badpass79401"
                    DSADD user -upn Paula.Warner@asazlab.com "cn=Paula.Warner,ou=UserAccounts,dc=asazlab,dc=com" -fn "Paula" -ln "Warner" -disabled no -display "Paula Warner" -desc "Defense Lab Of The Rectification Of Dysgenics Horse Breeder" -office "DevLabs Defense Lab Of The Rectification Of Dysgenics" -title "Horse Breeder" -company "DevLabs" -PWD "Badpass78584"
                    DSADD user -upn Samantha.Simpson@asazlab.com "cn=Samantha.Simpson,ou=UserAccounts,dc=asazlab,dc=com" -fn "Samantha" -ln "Simpson" -disabled no -display "SamanthaSimpson" -desc "Defense Lab Of The Rectification Of Dysgenics Horse Breeder" -office "DevLabs Defense Lab Of The Rectification Of Dysgenics" -title "Horse Breeder" -company "DevLabs" -PWD "Spring2021!"
                    DSADD user -upn Felix.Ballard@asazlab.com "cn=Felix.Ballard,ou=UserAccounts,dc=asazlab,dc=com" -fn "Felix" -ln "Ballard" -disabled no -display "Felix Ballard" -desc "Defense Lab Of The Rectification Of Dysgenics Livestock Breeder" -office "DevLabs Defense Lab Of The Rectification Of Dysgenics" -title "Livestock Breeder" -company "DevLabs" -PWD "Badpass6354"
                    DSADD user -upn Phyllis.Rivera@asazlab.com "cn=Phyllis.Rivera,ou=UserAccounts,dc=asazlab,dc=com" -fn "Phyllis" -ln "Rivera" -disabled no -display "Phyllis Rivera" -desc "Defense Lab Of The Rectification Of Dysgenics Poultry Inseminator" -office "DevLabs Defense Lab Of The Rectification Of Dysgenics" -title "Poultry Inseminator" -company "DevLabs" -PWD "Badpass82528"
                    DSADD user -upn Harriet.Moss@asazlab.com "cn=Harriet.Moss,ou=UserAccounts,dc=asazlab,dc=com" -fn "Harriet" -ln "Moss" -disabled no -display "Harriet Moss" -desc "Defense Lab Of The Rectification Of Dysgenics Stallion Manager" -office "DevLabs Defense Lab Of The Rectification Of Dysgenics" -title "Stallion Manager" -company "DevLabs" -PWD "Badpass21525"
                    DSADD user -upn Lucille.Tucker@asazlab.com "cn=Lucille.Tucker,ou=UserAccounts,dc=asazlab,dc=com" -fn "Lucille" -ln "Tucker" -disabled no -display "Lucille Tucker" -desc "Plutocratic Republic of Prefectures Rug Designer" -office "DevLabs Plutocratic Republic of Prefectures" -title "Rug Designer" -company "DevLabs" -PWD "Badpass7198"
                    DSADD user -upn Oscar.Sherman@asazlab.com "cn=Oscar.Sherman,ou=UserAccounts,dc=asazlab,dc=com" -fn "Oscar" -ln "Sherman" -disabled no -display "Oscar Sherman" -desc "Plutocratic Republic of Prefectures Special Education Preschool Teacher" -office "DevLabs Plutocratic Republic of Prefectures" -title "Special Education Preschool Teacher" -company "DevLabs" -PWD "Badpass26745"
                    DSADD user -upn Priscilla.Bryant@asazlab.com "cn=Priscilla.Bryant,ou=UserAccounts,dc=asazlab,dc=com" -fn "Priscilla" -ln "Bryant" -disabled no -display "Priscilla Bryant" -desc "Plutocratic Republic of Prefectures Radio Television Technical Director" -office "DevLabs Plutocratic Republic of Prefectures" -title "Radio Television Technical Director" -company "DevLabs" -PWD "Badpass37534"
                    DSADD user -upn Gwendolyn.Berry@asazlab.com "cn=Gwendolyn.Berry,ou=UserAccounts,dc=asazlab,dc=com" -fn "Gwendolyn" -ln "Berry" -disabled no -display "Gwendolyn Berry" -desc "Plutocratic Republic of Prefectures Rail Signal Mechanic" -office "DevLabs Plutocratic Republic of Prefectures" -title "Rail Signal Mechanic" -company "DevLabs" -PWD "Badpass16263"
                    DSADD user -upn Cynthia.Mcdonald@asazlab.com "cn=Cynthia.Mcdonald,ou=UserAccounts,dc=asazlab,dc=com" -fn "Cynthia" -ln "Mcdonald" -disabled no -display "Cynthia Mcdonald" -desc "Plutocratic Republic of Prefectures Funeral Arrangement Director" -office "DevLabs Plutocratic Republic of Prefectures" -title "Funeral Arrangement Director" -company "DevLabs" -PWD "Badpass67127"
                    DSADD user -upn Ignacio.Long@asazlab.com "cn=Ignacio.Long,ou=UserAccounts,dc=asazlab,dc=com" -fn "Ignacio" -ln "Long" -disabled no -display "Ignacio Long" -desc "Plutocratic Republic of Prefectures Tool Room Supervisor" -office "DevLabs Plutocratic Republic of Prefectures" -title "Tool Room Supervisor" -company "DevLabs" -PWD "Badpass59735"
                    DSADD user -upn Patsy.Medina@asazlab.com "cn=Patsy.Medina,ou=UserAccounts,dc=asazlab,dc=com" -fn "Patsy" -ln "Medina" -disabled no -display "Patsy Medina" -desc "Plutocratic Republic of Prefectures Non-Acoustic Operator" -office "DevLabs Plutocratic Republic of Prefectures" -title "Non-Acoustic Operator" -company "DevLabs" -PWD "Badpass58883"
                    DSADD user -upn Spencer.Watts@asazlab.com "cn=Spencer.Watts,ou=UserAccounts,dc=asazlab,dc=com" -fn "Spencer" -ln "Watts" -disabled no -display "Spencer Watts" -desc "Plutocratic Republic of Prefectures Foundry Molder" -office "DevLabs Plutocratic Republic of Prefectures" -title "Foundry Molder" -company "DevLabs" -PWD "Badpass11676"
                    DSADD user -upn Stuart.Poole@asazlab.com "cn=Stuart.Poole,ou=UserAccounts,dc=asazlab,dc=com" -fn "Stuart" -ln "Poole" -disabled no -display "Stuart Poole" -desc "Plutocratic Republic of Prefectures Coal Tram Driver" -office "DevLabs Plutocratic Republic of Prefectures" -title "Coal Tram Driver" -company "DevLabs" -PWD "Badpass68767"
                    DSADD user -upn Dana.Horton@asazlab.com "cn=Dana.Horton,ou=UserAccounts,dc=asazlab,dc=com" -fn "Dana" -ln "Horton" -disabled no -display "Dana Horton" -desc "Plutocratic Republic of Prefectures Cage Cashier" -office "DevLabs Plutocratic Republic of Prefectures" -title "Cage Cashier" -company "DevLabs" -PWD "Badpass89692"
                    DSADD user -upn Luz.Boone@asazlab.com "cn=Luz.Boone,ou=UserAccounts,dc=asazlab,dc=com" -fn "Luz" -ln "Boone" -disabled no -display "Luz Boone" -desc "Plutocratic Republic of Prefectures Golf Course Laborer" -office "DevLabs Plutocratic Republic of Prefectures" -title "Golf Course Laborer" -company "DevLabs" -PWD "Badpass6850"
                    DSADD user -upn Diane.Sims@asazlab.com "cn=Diane.Sims,ou=UserAccounts,dc=asazlab,dc=com" -fn "Diane" -ln "Sims" -disabled no -display "Diane Sims" -desc "Plutocratic Republic of Prefectures Aegis Console Operator Track 3" -office "DevLabs Plutocratic Republic of Prefectures" -title "Aegis Console Operator Track 3" -company "DevLabs" -PWD "Badpass10158"
                    DSADD user -upn Joanne.Stewart@asazlab.com "cn=Joanne.Stewart,ou=UserAccounts,dc=asazlab,dc=com" -fn "Joanne" -ln "Stewart" -disabled no -display "Joanne Stewart" -desc "Plutocratic Republic of Prefectures Dairy Husbandry Worker" -office "DevLabs Plutocratic Republic of Prefectures" -title "Dairy Husbandry Worker" -company "DevLabs" -PWD "Badpass19993"
                    DSADD user -upn Wallace.West@asazlab.com "cn=Wallace.West,ou=UserAccounts,dc=asazlab,dc=com" -fn "Wallace" -ln "West" -disabled no -display "Wallace West" -desc "Plutocratic Republic of Prefectures Airborne Mission Systems Superintendent" -office "DevLabs Plutocratic Republic of Prefectures" -title "Airborne Mission Systems Superintendent" -company "DevLabs" -PWD "Badpass61788"
                    DSADD user -upn Nellie.Higgins@asazlab.com "cn=Nellie.Higgins,ou=UserAccounts,dc=asazlab,dc=com" -fn "Nellie" -ln "Higgins" -disabled no -display "Nellie Higgins" -desc "Plutocratic Republic of Prefectures An/Sqq-32(V)3 Minehunting Sonar Set Operator (Mss)" -office "DevLabs Plutocratic Republic of Prefectures" -title "An/Sqq-32(V)3 Minehunting Sonar Set Operator (Mss)" -company "DevLabs" -PWD "Badpass85310"
                    DSADD user -upn Gabriel.Roberson@asazlab.com "cn=Gabriel.Roberson,ou=UserAccounts,dc=asazlab,dc=com" -fn "Gabriel" -ln "Roberson" -disabled no -display "Gabriel Roberson" -desc "Plutocratic Republic of Prefectures Certified Mortician" -office "DevLabs Plutocratic Republic of Prefectures" -title "Certified Mortician" -company "DevLabs" -PWD "Badpass61561"
                    DSADD user -upn Roberto.Lyons@asazlab.com "cn=Roberto.Lyons,ou=UserAccounts,dc=asazlab,dc=com" -fn "Roberto" -ln "Lyons" -disabled no -display "Roberto Lyons" -desc "The Light Academy National Association for Stock Car Auto Racing Driver" -office "DevLabs The Light Academy" -title "National Association for Stock Car Auto Racing Driver" -company "DevLabs" -PWD "Badpass52164"
                    DSADD user -upn Beverly.Lucas@asazlab.com "cn=Beverly.Lucas,ou=UserAccounts,dc=asazlab,dc=com" -fn "Beverly" -ln "Lucas" -disabled no -display "Beverly Lucas" -desc "The Light Academy Souvenir Street Vendor" -office "DevLabs The Light Academy" -title "Souvenir Street Vendor" -company "DevLabs" -PWD "Badpass1874"
                    DSADD user -upn Dorothy.Pearson@asazlab.com "cn=Dorothy.Pearson,ou=UserAccounts,dc=asazlab,dc=com" -fn "Dorothy" -ln "Pearson" -disabled no -display "Dorothy Pearson" -desc "The Light Academy Conductor" -office "DevLabs The Light Academy" -title "Conductor" -company "DevLabs" -PWD "Badpass76416"
                    DSADD user -upn Glen.Shaw@asazlab.com "cn=Glen.Shaw,ou=UserAccounts,dc=asazlab,dc=com" -fn "Glen" -ln "Shaw" -disabled no -display "Glen Shaw" -desc "The Light Academy Meter Maid" -office "DevLabs The Light Academy" -title "Meter Maid" -company "DevLabs" -PWD "Badpass17321"
                    DSADD user -upn Ginger.Wilkins@asazlab.com "cn=Ginger.Wilkins,ou=UserAccounts,dc=asazlab,dc=com" -fn "Ginger" -ln "Wilkins" -disabled no -display "Ginger Wilkins" -desc "The Light Academy Victorian Literature Professor" -office "DevLabs The Light Academy" -title "Victorian Literature Professor" -company "DevLabs" -PWD "Badpass56275"
                    DSADD user -upn Leona.Wallace@asazlab.com "cn=Leona.Wallace,ou=UserAccounts,dc=asazlab,dc=com" -fn "Leona" -ln "Wallace" -disabled no -display "Leona Wallace" -desc "The Light Academy Deck Cadet" -office "DevLabs The Light Academy" -title "Deck Cadet" -company "DevLabs" -PWD "Badpass80651"
                    DSADD user -upn Chester.Dean@asazlab.com "cn=Chester.Dean,ou=UserAccounts,dc=asazlab,dc=com" -fn "Chester" -ln "Dean" -disabled no -display "Chester Dean" -desc "The Light Academy Objects Conservator" -office "DevLabs The Light Academy" -title "Objects Conservator" -company "DevLabs" -PWD "Badpass21023"
                    DSADD user -upn Rosalie.Torres@asazlab.com "cn=Rosalie.Torres,ou=UserAccounts,dc=asazlab,dc=com" -fn "Rosalie" -ln "Torres" -disabled no -display "Rosalie Torres" -desc "The Light Academy Naval Aircrewman Avionics" -office "DevLabs The Light Academy" -title "Naval Aircrewman Avionics" -company "DevLabs" -PWD "Badpass62974"
                    DSADD user -upn Gerardo.Ross@asazlab.com "cn=Gerardo.Ross,ou=UserAccounts,dc=asazlab,dc=com" -fn "Gerardo" -ln "Ross" -disabled no -display "Gerardo Ross" -desc "The Light Academy Real Estate Loan Officer" -office "DevLabs The Light Academy" -title "Real Estate Loan Officer" -company "DevLabs" -PWD "Badpass97522"
                    DSADD user -upn Charlene.Shelton@asazlab.com "cn=Charlene.Shelton,ou=UserAccounts,dc=asazlab,dc=com" -fn "Charlene" -ln "Shelton" -disabled no -display "Charlene Shelton" -desc "The Light Academy Pipe Fitter" -office "DevLabs The Light Academy" -title "Pipe Fitter" -company "DevLabs" -PWD "Badpass47743"
                    DSADD user -upn Joyce.Jefferson@asazlab.com "cn=Joyce.Jefferson,ou=UserAccounts,dc=asazlab,dc=com" -fn "Joyce" -ln "Jefferson" -disabled no -display "Joyce Jefferson" -desc "Integrated Gyrohands Television Repairer" -office "DevLabs Integrated Gyrohands" -title "Television Repairer" -company "DevLabs" -PWD "Badpass4557"
                    DSADD user -upn Damon.Rodriguez@asazlab.com "cn=Damon.Rodriguez,ou=UserAccounts,dc=asazlab,dc=com" -fn "Damon" -ln "Rodriguez" -disabled no -display "Damon Rodriguez" -desc "Protonic Distortion Wardrobe Custodian" -office "DevLabs Protonic Distortion" -title "Wardrobe Custodian" -company "DevLabs" -PWD "Badpass82446"
                    DSADD user -upn Oliver.Barton@asazlab.com "cn=Oliver.Barton,ou=UserAccounts,dc=asazlab,dc=com" -fn "Oliver" -ln "Barton" -disabled no -display "Oliver Barton" -desc "Office of Programming Troubleshooting and Application Security Highway Inspector" -office "DevLabs Office of Programming Troubleshooting and Application Security" -title "Highway Inspector" -company "DevLabs" -PWD "Badpass10237"
                    DSADD user -upn Janis.Sutton@asazlab.com "cn=Janis.Sutton,ou=UserAccounts,dc=asazlab,dc=com" -fn "Janis" -ln "Sutton" -disabled no -display "Janis Sutton" -desc "Office of Programming Troubleshooting and Application Security Mortgage Closing Clerk" -office "DevLabs Office of Programming Troubleshooting and Application Security" -title "Mortgage Closing Clerk" -company "DevLabs" -PWD "Badpass48899"
                    DSADD user -upn Paul.Moran@asazlab.com "cn=Paul.Moran,ou=UserAccounts,dc=asazlab,dc=com" -fn "Paul" -ln "Moran" -disabled no -display "Paul Moran" -desc "Office of Programming Troubleshooting and Application Security Journalism Professor" -office "DevLabs Office of Programming Troubleshooting and Application Security" -title "Journalism Professor" -company "DevLabs" -PWD "Badpass55810"
                    DSADD user -upn Enrique.Gomez@asazlab.com "cn=Enrique.Gomez,ou=UserAccounts,dc=asazlab,dc=com" -fn "Enrique" -ln "Gomez" -disabled no -display "Enrique Gomez" -desc "Office of Programming Troubleshooting and Application Security Vacuum Cleaner Repair Person" -office "DevLabs Office of Programming Troubleshooting and Application Security" -title "Vacuum Cleaner Repair Person" -company "DevLabs" -PWD "Badpass71668"
                    DSADD user -upn Walter.Cannon@asazlab.com "cn=Walter.Cannon,ou=UserAccounts,dc=asazlab,dc=com" -fn "Walter" -ln "Cannon" -disabled no -display "Walter Cannon" -desc "Office of Programming Troubleshooting and Application Security Paddock Judge" -office "DevLabs Office of Programming Troubleshooting and Application Security" -title "Paddock Judge" -company "DevLabs" -PWD "Badpass61960"
                    DSADD user -upn Antonio.Garza@asazlab.com "cn=Antonio.Garza,ou=UserAccounts,dc=asazlab,dc=com" -fn "Antonio" -ln "Garza" -disabled no -display "Antonio Garza" -desc "Office of Programming Troubleshooting and Application Security Aviation Ordnance Officer" -office "DevLabs Office of Programming Troubleshooting and Application Security" -title "Aviation Ordnance Officer" -company "DevLabs" -PWD "Badpass5241"
                    DSADD user -upn Kent.Sullivan@asazlab.com "cn=Kent.Sullivan,ou=UserAccounts,dc=asazlab,dc=com" -fn "Kent" -ln "Sullivan" -disabled no -display "Kent Sullivan" -desc "Office of Programming Troubleshooting and Application Security Career Technical Counselor" -office "DevLabs Office of Programming Troubleshooting and Application Security" -title "Career Technical Counselor" -company "DevLabs" -PWD "Badpass17022"
                    DSADD user -upn Sonia.Griffith@asazlab.com "cn=Sonia.Griffith,ou=UserAccounts,dc=asazlab,dc=com" -fn "Sonia" -ln "Griffith" -disabled no -display "Sonia Griffith" -desc "Office of Programming Troubleshooting and Application Security Maxillofacial Prosthodontist" -office "DevLabs Office of Programming Troubleshooting and Application Security" -title "Maxillofacial Prosthodontist" -company "DevLabs" -PWD "Badpass11371"
                    DSADD user -upn Jean.Ross@asazlab.com "cn=Jean.Ross,ou=UserAccounts,dc=asazlab,dc=com" -fn "Jean" -ln "Ross" -disabled no -display "Jean Ross" -desc "Office of Programming Troubleshooting and Application Security Stoker Installer" -office "DevLabs Office of Programming Troubleshooting and Application Security" -title "Stoker Installer" -company "DevLabs" -PWD "Badpass15372"
                    DSADD user -upn Kerry.Byrd@asazlab.com "cn=Kerry.Byrd,ou=UserAccounts,dc=asazlab,dc=com" -fn "Kerry" -ln "Byrd" -disabled no -display "Kerry Byrd" -desc "Office of Programming Troubleshooting and Application Security Billiard Player" -office "DevLabs Office of Programming Troubleshooting and Application Security" -title "Billiard Player" -company "DevLabs" -PWD "Badpass73384"
                    DSADD user -upn Wallace.Watson@asazlab.com "cn=Wallace.Watson,ou=UserAccounts,dc=asazlab,dc=com" -fn "Wallace" -ln "Watson" -disabled no -display "Wallace Watson" -desc "PC Troubleshooting Branch Foreign Exchange Position Clerk" -office "DevLabs PC Troubleshooting Branch" -title "Foreign Exchange Position Clerk" -company "DevLabs" -PWD "Badpass37450"
                    DSADD user -upn Jill.Campbell@asazlab.com "cn=Jill.Campbell,ou=UserAccounts,dc=asazlab,dc=com" -fn "Jill" -ln "Campbell" -disabled no -display "Jill Campbell" -desc "PC Troubleshooting Branch Estate Conservator" -office "DevLabs PC Troubleshooting Branch" -title "Estate Conservator" -company "DevLabs" -PWD "Badpass25598"
                    DSADD user -upn Regina.Neal@asazlab.com "cn=Regina.Neal,ou=UserAccounts,dc=asazlab,dc=com" -fn "Regina" -ln "Neal" -disabled no -display "Regina Neal" -desc "PC Troubleshooting Branch Mortgage Accounting Clerk" -office "DevLabs PC Troubleshooting Branch" -title "Mortgage Accounting Clerk" -company "DevLabs" -PWD "Badpass38541"
                    DSADD user -upn Vanessa.Floyd@asazlab.com "cn=Vanessa.Floyd,ou=UserAccounts,dc=asazlab,dc=com" -fn "Vanessa" -ln "Floyd" -disabled no -display "Vanessa Floyd" -desc "PC Troubleshooting Branch Economic Geographer" -office "DevLabs PC Troubleshooting Branch" -title "Economic Geographer" -company "DevLabs" -PWD "Badpass82092"
                    DSADD user -upn Essie.Mclaughlin@asazlab.com "cn=Essie.Mclaughlin,ou=UserAccounts,dc=asazlab,dc=com" -fn "Essie" -ln "Mclaughlin" -disabled no -display "Essie Mclaughlin" -desc "PC Troubleshooting Branch Head Greenskeeper" -office "DevLabs PC Troubleshooting Branch" -title "Head Greenskeeper" -company "DevLabs" -PWD "Badpass30530"
                    DSADD user -upn Dana.Johnson@asazlab.com "cn=Dana.Johnson,ou=UserAccounts,dc=asazlab,dc=com" -fn "Dana" -ln "Johnson" -disabled no -display "Dana Johnson" -desc "PC Troubleshooting Branch Public Affairs Officer" -office "DevLabs PC Troubleshooting Branch" -title "Public Affairs Officer" -company "DevLabs" -PWD "Badpass41884"
                    DSADD user -upn Mona.Ballard@asazlab.com "cn=Mona.Ballard,ou=UserAccounts,dc=asazlab,dc=com" -fn "Mona" -ln "Ballard" -disabled no -display "Mona Ballard" -desc "PC Troubleshooting Branch Manufacturing Engineering Professor" -office "DevLabs PC Troubleshooting Branch" -title "Manufacturing Engineering Professor" -company "DevLabs" -PWD "Badpass82899"
                    DSADD user -upn Santiago.Parks@asazlab.com "cn=Santiago.Parks,ou=UserAccounts,dc=asazlab,dc=com" -fn "Santiago" -ln "Parks" -disabled no -display "Santiago Parks" -desc "PC Troubleshooting Branch Drug Abuse Counselor" -office "DevLabs PC Troubleshooting Branch" -title "Drug Abuse Counselor" -company "DevLabs" -PWD "Badpass67974"
                    DSADD user -upn Cristina.Page@asazlab.com "cn=Cristina.Page,ou=UserAccounts,dc=asazlab,dc=com" -fn "Cristina" -ln "Page" -disabled no -display "Cristina Page" -desc "PC Troubleshooting Branch Airborne Operations Manager" -office "DevLabs PC Troubleshooting Branch" -title "Airborne Operations Manager" -company "DevLabs" -PWD "Badpass4564"
                    DSADD user -upn Harvey.Brady@asazlab.com "cn=Harvey.Brady,ou=UserAccounts,dc=asazlab,dc=com" -fn "Harvey" -ln "Brady" -disabled no -display "Harvey Brady" -desc "PC Troubleshooting Branch Florist" -office "DevLabs PC Troubleshooting Branch" -title "Florist" -company "DevLabs" -PWD "Badpass98763"
                    DSADD user -upn Grace.Turner@asazlab.com "cn=Grace.Turner,ou=UserAccounts,dc=asazlab,dc=com" -fn "Grace" -ln "Turner" -disabled no -display "Grace Turner" -desc "Agency of Portable PC Implementation Stage Electrician" -office "DevLabs Agency of Portable PC Implementation" -title "Stage Electrician" -company "DevLabs" -PWD "Badpass79900"
                    DSADD user -upn Katie.Maxwell@asazlab.com "cn=Katie.Maxwell,ou=UserAccounts,dc=asazlab,dc=com" -fn "Katie" -ln "Maxwell" -disabled no -display "Katie Maxwell" -desc "Agency of Portable PC Implementation Bilingual Kindergarten Teacher" -office "DevLabs Agency of Portable PC Implementation" -title "Bilingual Kindergarten Teacher" -company "DevLabs" -PWD "Badpass23686"
                    DSADD user -upn Don.Potter@asazlab.com "cn=Don.Potter,ou=UserAccounts,dc=asazlab,dc=com" -fn "Don" -ln "Potter" -disabled no -display "Don Potter" -desc "Agency of Portable PC Implementation Construction Ironworker Helper" -office "DevLabs Agency of Portable PC Implementation" -title "Construction Ironworker Helper" -company "DevLabs" -PWD "Badpass82814"
                    DSADD user -upn Loren.Elliott@asazlab.com "cn=Loren.Elliott,ou=UserAccounts,dc=asazlab,dc=com" -fn "Loren" -ln "Elliott" -disabled no -display "Loren Elliott" -desc "Agency of Portable PC Implementation Visual Merchandiser" -office "DevLabs Agency of Portable PC Implementation" -title "Visual Merchandiser" -company "DevLabs" -PWD "Badpass11447"
                    DSADD user -upn Marcia.Fitzgerald@asazlab.com "cn=Marcia.Fitzgerald,ou=UserAccounts,dc=asazlab,dc=com" -fn "Marcia" -ln "Fitzgerald" -disabled no -display "Marcia Fitzgerald" -desc "Agency of Portable PC Implementation Telesales Supervisor" -office "DevLabs Agency of Portable PC Implementation" -title "Telesales Supervisor" -company "DevLabs" -PWD "Badpass88006"
                    DSADD user -upn Sylvia.Sutton@asazlab.com "cn=Sylvia.Sutton,ou=UserAccounts,dc=asazlab,dc=com" -fn "Sylvia" -ln "Sutton" -disabled no -display "Sylvia Sutton" -desc "Agency of Portable PC Implementation Fire Control Officer" -office "DevLabs Agency of Portable PC Implementation" -title "Fire Control Officer" -company "DevLabs" -PWD "Badpass11813"
                    DSADD user -upn Rosemary.Peterson@asazlab.com "cn=Rosemary.Peterson,ou=UserAccounts,dc=asazlab,dc=com" -fn "Rosemary" -ln "Peterson" -disabled no -display "Rosemary Peterson" -desc "Code Security and PC Technology Team Cement Truck Driver" -office "DevLabs Code Security and PC Technology Team" -title "Cement Truck Driver" -company "DevLabs" -PWD "Badpass44039"
                    DSADD user -upn Anthony.Caldwell@asazlab.com "cn=Anthony.Caldwell,ou=UserAccounts,dc=asazlab,dc=com" -fn "Anthony" -ln "Caldwell" -disabled no -display "Anthony Caldwell" -desc "Code Security and PC Technology Team Window Cleaner" -office "DevLabs Code Security and PC Technology Team" -title "Window Cleaner" -company "DevLabs" -PWD "Badpass78369"
                    DSADD user -upn Brooke.Webster@asazlab.com "cn=Brooke.Webster,ou=UserAccounts,dc=asazlab,dc=com" -fn "Brooke" -ln "Webster" -disabled no -display "Brooke Webster" -desc "Code Security and PC Technology Team Licensed Clinical Mental Health Counselor" -office "DevLabs Code Security and PC Technology Team" -title "Licensed Clinical Mental Health Counselor" -company "DevLabs" -PWD "Badpass22968"
                    DSADD user -upn Penny.Gregory@asazlab.com "cn=Penny.Gregory,ou=UserAccounts,dc=asazlab,dc=com" -fn "Penny" -ln "Gregory" -disabled no -display "Penny Gregory" -desc "Code Security and PC Technology Team Store Gift Wrap Associate" -office "DevLabs Code Security and PC Technology Team" -title "Store Gift Wrap Associate" -company "DevLabs" -PWD "Badpass29522"
                    DSADD user -upn Dominic.Mendoza@asazlab.com "cn=Dominic.Mendoza,ou=UserAccounts,dc=asazlab,dc=com" -fn "Dominic" -ln "Mendoza" -disabled no -display "Dominic Mendoza" -desc "Code Security and PC Technology Team Traveling Missionary" -office "DevLabs Code Security and PC Technology Team" -title "Traveling Missionary" -company "DevLabs" -PWD "Badpass45551"
                    DSADD user -upn Ethel.Bishop@asazlab.com "cn=Ethel.Bishop,ou=UserAccounts,dc=asazlab,dc=com" -fn "Ethel" -ln "Bishop" -disabled no -display "Ethel Bishop" -desc "Code Security and PC Technology Team Tax Compliance Representative" -office "DevLabs Code Security and PC Technology Team" -title "Tax Compliance Representative" -company "DevLabs" -PWD "Badpass14715"
                    DSADD user -upn Kelvin.Ortiz@asazlab.com "cn=Kelvin.Ortiz,ou=UserAccounts,dc=asazlab,dc=com" -fn "Kelvin" -ln "Ortiz" -disabled no -display "Kelvin Ortiz" -desc "Code Security and PC Technology Team Hotel Baggage Handler" -office "DevLabs Code Security and PC Technology Team" -title "Hotel Baggage Handler" -company "DevLabs" -PWD "Badpass73993"
                    DSADD user -upn Caleb.Kennedy@asazlab.com "cn=Caleb.Kennedy,ou=UserAccounts,dc=asazlab,dc=com" -fn "Caleb" -ln "Kennedy" -disabled no -display "Caleb Kennedy" -desc "Code Security and PC Technology Team Registered Medical Transcriptionist" -office "DevLabs Code Security and PC Technology Team" -title "Registered Medical Transcriptionist" -company "DevLabs" -PWD "Badpass76530"
                    DSADD user -upn Randal.Parsons@asazlab.com "cn=Randal.Parsons,ou=UserAccounts,dc=asazlab,dc=com" -fn "Randal" -ln "Parsons" -disabled no -display "Randal Parsons" -desc "Code Security and PC Technology Team Pugilist" -office "DevLabs Code Security and PC Technology Team" -title "Pugilist" -company "DevLabs" -PWD "Badpass11028"
                    DSADD user -upn Seth.Harper@asazlab.com "cn=Seth.Harper,ou=UserAccounts,dc=asazlab,dc=com" -fn "Seth" -ln "Harper" -disabled no -display "Seth Harper" -desc "Code Security and PC Technology Team Wholesale Ultrasonic Equipment Salesperson" -office "DevLabs Code Security and PC Technology Team" -title "Wholesale Ultrasonic Equipment Salesperson" -company "DevLabs" -PWD "Badpass74210"
                    DSADD user -upn Debra.Thornton@asazlab.com "cn=Debra.Thornton,ou=UserAccounts,dc=asazlab,dc=com" -fn "Debra" -ln "Thornton" -disabled no -display "Debra Thornton" -desc "Illuminated Technocracy Sports Complex Attendant" -office "DevLabs Illuminated Technocracy" -title "Sports Complex Attendant" -company "DevLabs" -PWD "Badpass84977"
                    DSADD user -upn Jessie.Schmidt@asazlab.com "cn=Jessie.Schmidt,ou=UserAccounts,dc=asazlab,dc=com" -fn "Jessie" -ln "Schmidt" -disabled no -display "Jessie Schmidt" -desc "Illuminated Technocracy Boiler Operator" -office "DevLabs Illuminated Technocracy" -title "Boiler Operator" -company "DevLabs" -PWD "Badpass44945"
                    DSADD user -upn Antoinette.Morrison@asazlab.com "cn=Antoinette.Morrison,ou=UserAccounts,dc=asazlab,dc=com" -fn "Antoinette" -ln "Morrison" -disabled no -display "Antoinette Morrison" -desc "Illuminated Technocracy Booking Manager" -office "DevLabs Illuminated Technocracy" -title "Booking Manager" -company "DevLabs" -PWD "Badpass96146"
                    DSADD user -upn Mark.Mccormick@asazlab.com "cn=Mark.Mccormick,ou=UserAccounts,dc=asazlab,dc=com" -fn "Mark" -ln "Mccormick" -disabled no -display "Mark Mccormick" -desc "Illuminated Technocracy Registered Medical Transcriptionist" -office "DevLabs Illuminated Technocracy" -title "Registered Medical Transcriptionist" -company "DevLabs" -PWD "Badpass43688"
                    DSADD user -upn Jeanette.Wise@asazlab.com "cn=Jeanette.Wise,ou=UserAccounts,dc=asazlab,dc=com" -fn "Jeanette" -ln "Wise" -disabled no -display "Jeanette Wise" -desc "Illuminated Technocracy Tape Editor" -office "DevLabs Illuminated Technocracy" -title "Tape Editor" -company "DevLabs" -PWD "Badpass56301"
                    DSADD user -upn Elena.Hernandez@asazlab.com "cn=Elena.Hernandez,ou=UserAccounts,dc=asazlab,dc=com" -fn "Elena" -ln "Hernandez" -disabled no -display "Elena Hernandez" -desc "Illuminated Technocracy Cotton Ginner" -office "DevLabs Illuminated Technocracy" -title "Cotton Ginner" -company "DevLabs" -PWD "Badpass95861"
                    DSADD user -upn Bob.King@asazlab.com "cn=Bob.King,ou=UserAccounts,dc=asazlab,dc=com" -fn "Bob" -ln "King" -disabled no -display "Bob King" -desc "Radioactive Team Glacier Music Adapter" -office "DevLabs Radioactive Team Glacier" -title "Music Adapter" -company "DevLabs" -PWD "Badpass46339"
                    DSADD user -upn Vera.Daniels@asazlab.com "cn=Vera.Daniels,ou=UserAccounts,dc=asazlab,dc=com" -fn "Vera" -ln "Daniels" -disabled no -display "Vera Daniels" -desc "Radioactive Team Glacier Poultry Inseminator" -office "DevLabs Radioactive Team Glacier" -title "Poultry Inseminator" -company "DevLabs" -PWD "Badpass78347"
                    DSADD user -upn Colleen.Blair@asazlab.com "cn=Colleen.Blair,ou=UserAccounts,dc=asazlab,dc=com" -fn "Colleen" -ln "Blair" -disabled no -display "Colleen Blair" -desc "Radioactive Team Glacier DTR" -office "DevLabs Radioactive Team Glacier" -title "DTR" -company "DevLabs" -PWD "Badpass19252"
                    DSADD user -upn Arlene.Poole@asazlab.com "cn=Arlene.Poole,ou=UserAccounts,dc=asazlab,dc=com" -fn "Arlene" -ln "Poole" -disabled no -display "Arlene Poole" -desc "Radioactive Team Glacier Songwriter" -office "DevLabs Radioactive Team Glacier" -title "Songwriter" -company "DevLabs" -PWD "Badpass78687"
                    DSADD user -upn Stella.Palmer@asazlab.com "cn=Stella.Palmer,ou=UserAccounts,dc=asazlab,dc=com" -fn "Stella" -ln "Palmer" -disabled no -display "Stella Palmer" -desc "Radioactive Team Glacier Bicycle Racer" -office "DevLabs Radioactive Team Glacier" -title "Bicycle Racer" -company "DevLabs" -PWD "Badpass77917"
                    DSADD user -upn Phil.Hogan@asazlab.com "cn=Phil.Hogan,ou=UserAccounts,dc=asazlab,dc=com" -fn "Phil" -ln "Hogan" -disabled no -display "Phil Hogan" -desc "Radioactive Team Glacier Certified Nurse Midwife (CNM)" -office "DevLabs Radioactive Team Glacier" -title "Certified Nurse Midwife (CNM)" -company "DevLabs" -PWD "Badpass69445"
                    DSADD user -upn Angelo.Richards@asazlab.com "cn=Angelo.Richards,ou=UserAccounts,dc=asazlab,dc=com" -fn "Angelo" -ln "Richards" -disabled no -display "Angelo Richards" -desc "Radioactive Team Glacier Field Enumerator" -office "DevLabs Radioactive Team Glacier" -title "Field Enumerator" -company "DevLabs" -PWD "Badpass97334"
                    DSADD user -upn Jasmine.Lawson@asazlab.com "cn=Jasmine.Lawson,ou=UserAccounts,dc=asazlab,dc=com" -fn "Jasmine" -ln "Lawson" -disabled no -display "Jasmine Lawson" -desc "Radioactive Team Glacier Industrial Photographer" -office "DevLabs Radioactive Team Glacier" -title "Industrial Photographer" -company "DevLabs" -PWD "Badpass30977"
                    DSADD user -upn Julio.Davis@asazlab.com "cn=Julio.Davis,ou=UserAccounts,dc=asazlab,dc=com" -fn "Julio" -ln "Davis" -disabled no -display "Julio Davis" -desc "Radioactive Team Glacier Early Childhood Special Education Teacher" -office "DevLabs Radioactive Team Glacier" -title "Early Childhood Special Education Teacher" -company "DevLabs" -PWD "Badpass46270"
                    DSADD user -upn Monique.Price@asazlab.com "cn=Monique.Price,ou=UserAccounts,dc=asazlab,dc=com" -fn "Monique" -ln "Price" -disabled no -display "Monique Price" -desc "Radioactive Team Glacier Telephone Interviewer" -office "DevLabs Radioactive Team Glacier" -title "Telephone Interviewer" -company "DevLabs" -PWD "Badpass788"
                    DSADD user -upn Gerardo.Lindsey@asazlab.com "cn=Gerardo.Lindsey,ou=UserAccounts,dc=asazlab,dc=com" -fn "Gerardo" -ln "Lindsey" -disabled no -display "Gerardo Lindsey" -desc "Radioactive Team Glacier Adult Nurse Practitioner" -office "DevLabs Radioactive Team Glacier" -title "Adult Nurse Practitioner" -company "DevLabs" -PWD "Badpass96589"
                    DSADD user -upn Terrence.Chapman@asazlab.com "cn=Terrence.Chapman,ou=UserAccounts,dc=asazlab,dc=com" -fn "Terrence" -ln "Chapman" -disabled no -display "Terrence Chapman" -desc "Radioactive Team Glacier Airset Caster" -office "DevLabs Radioactive Team Glacier" -title "Airset Caster" -company "DevLabs" -PWD "Badpass68831"
                    DSADD user -upn Horace.Alvarado@asazlab.com "cn=Horace.Alvarado,ou=UserAccounts,dc=asazlab,dc=com" -fn "Horace" -ln "Alvarado" -disabled no -display "Horace Alvarado" -desc "Radioactive Team Glacier Counterintelligence/Human Intelligence, Senior Sergeant" -office "DevLabs Radioactive Team Glacier" -title "Counterintelligence/Human Intelligence, Senior Sergeant" -company "DevLabs" -PWD "Badpass13042"
                    DSADD user -upn Jeannie.Jacobs@asazlab.com "cn=Jeannie.Jacobs,ou=UserAccounts,dc=asazlab,dc=com" -fn "Jeannie" -ln "Jacobs" -disabled no -display "Jeannie Jacobs" -desc "Radioactive Team Glacier Ship Purser" -office "DevLabs Radioactive Team Glacier" -title "Ship Purser" -company "DevLabs" -PWD "Badpass55527"
                    DSADD user -upn Irvin.May@asazlab.com "cn=Irvin.May,ou=UserAccounts,dc=asazlab,dc=com" -fn "Irvin" -ln "May" -disabled no -display "Irvin May" -desc "Radioactive Team Glacier Poker Room Supervisor" -office "DevLabs Radioactive Team Glacier" -title "Poker Room Supervisor" -company "DevLabs" -PWD "Badpass60479"
                    DSADD user -upn Rafael.Colon@asazlab.com "cn=Rafael.Colon,ou=UserAccounts,dc=asazlab,dc=com" -fn "Rafael" -ln "Colon" -disabled no -display "Rafael Colon" -desc "Radioactive Team Glacier Licensed Massage Therapist" -office "DevLabs Radioactive Team Glacier" -title "Licensed Massage Therapist" -company "DevLabs" -PWD "Badpass40962"
                    DSADD user -upn Gertrude.Kim@asazlab.com "cn=Gertrude.Kim,ou=UserAccounts,dc=asazlab,dc=com" -fn "Gertrude" -ln "Kim" -disabled no -display "Gertrude Kim" -desc "Titanium Task Force Magnetic Fire Control Officer" -office "DevLabs Titanium Task Force Magnetic" -title "Fire Control Officer" -company "DevLabs" -PWD "Badpass87915"
                    DSADD user -upn Angela.Knight@asazlab.com "cn=Angela.Knight,ou=UserAccounts,dc=asazlab,dc=com" -fn "Angela" -ln "Knight" -disabled no -display "Angela Knight" -desc "Titanium Task Force Magnetic Motor Rewinder" -office "DevLabs Titanium Task Force Magnetic" -title "Motor Rewinder" -company "DevLabs" -PWD "Badpass80578"
                    DSADD user -upn Janie.Goodwin@asazlab.com "cn=Janie.Goodwin,ou=UserAccounts,dc=asazlab,dc=com" -fn "Janie" -ln "Goodwin" -disabled no -display "Janie Goodwin" -desc "Titanium Task Force Magnetic Airplane Refueler" -office "DevLabs Titanium Task Force Magnetic" -title "Airplane Refueler" -company "DevLabs" -PWD "Badpass83974"
                    DSADD user -upn Stephen.Mckinney@asazlab.com "cn=Stephen.Mckinney,ou=UserAccounts,dc=asazlab,dc=com" -fn "Stephen" -ln "Mckinney" -disabled no -display "Stephen Mckinney" -desc "Titanium Task Force Magnetic Marine Architect" -office "DevLabs Titanium Task Force Magnetic" -title "Marine Architect" -company "DevLabs" -PWD "Badpass73138"
                    DSADD user -upn Eleanor.Abbott@asazlab.com "cn=Eleanor.Abbott,ou=UserAccounts,dc=asazlab,dc=com" -fn "Eleanor" -ln "Abbott" -disabled no -display "Eleanor Abbott" -desc "Titanium Task Force Magnetic Harvest Crew Supervisor" -office "DevLabs Titanium Task Force Magnetic" -title "Harvest Crew Supervisor" -company "DevLabs" -PWD "Badpass68"
                    DSADD user -upn Perry.Newman@asazlab.com "cn=Perry.Newman,ou=UserAccounts,dc=asazlab,dc=com" -fn "Perry" -ln "Newman" -disabled no -display "Perry Newman" -desc "Titanium Task Force Magnetic Compressor Station Operator" -office "DevLabs Titanium Task Force Magnetic" -title "Compressor Station Operator" -company "DevLabs" -PWD "Badpass2396"
                    DSADD user -upn Dan.Richardson@asazlab.com "cn=Dan.Richardson,ou=UserAccounts,dc=asazlab,dc=com" -fn "Dan" -ln "Richardson" -disabled no -display "Dan Richardson" -desc "Titanium Task Force Magnetic Street Sweeper Operator" -office "DevLabs Titanium Task Force Magnetic" -title "Street Sweeper Operator" -company "DevLabs" -PWD "Badpass6205"
                    DSADD user -upn Kim.Dennis@asazlab.com "cn=Kim.Dennis,ou=UserAccounts,dc=asazlab,dc=com" -fn "Kim" -ln "Dennis" -disabled no -display "Kim Dennis" -desc "Titanium Task Force Magnetic Submarine Diver" -office "DevLabs Titanium Task Force Magnetic" -title "Submarine Diver" -company "DevLabs" -PWD "Badpass73923"
                    DSADD user -upn Hattie.Henry@asazlab.com "cn=Hattie.Henry,ou=UserAccounts,dc=asazlab,dc=com" -fn "Hattie" -ln "Henry" -disabled no -display "Hattie Henry" -desc "Titanium Task Force Magnetic Paraeducator" -office "DevLabs Titanium Task Force Magnetic" -title "Paraeducator" -company "DevLabs" -PWD "Badpass49354"
                    DSADD user -upn Katrina.Frazier@asazlab.com "cn=Katrina.Frazier,ou=UserAccounts,dc=asazlab,dc=com" -fn "Katrina" -ln "Frazier" -disabled no -display "Katrina Frazier" -desc "Titanium Task Force Magnetic Clinical Social Work Aide" -office "DevLabs Titanium Task Force Magnetic" -title "Clinical Social Work Aide" -company "DevLabs" -PWD "Badpass14909"
                    DSADD user -upn Christie.Hubbard@asazlab.com "cn=Christie.Hubbard,ou=UserAccounts,dc=asazlab,dc=com" -fn "Christie" -ln "Hubbard" -disabled no -display "Christie Hubbard" -desc "Uranium Squadron Grocery Stocker" -office "DevLabs Uranium Squadron" -title "Grocery Stocker" -company "DevLabs" -PWD "Badpass91353"
                    DSADD user -upn Johnnie.Doyle@asazlab.com "cn=Johnnie.Doyle,ou=UserAccounts,dc=asazlab,dc=com" -fn "Johnnie" -ln "Doyle" -disabled no -display "Johnnie Doyle" -desc "Uranium Squadron Laryngologist" -office "DevLabs Uranium Squadron" -title "Laryngologist" -company "DevLabs" -PWD "Badpass7531"
                    DSADD user -upn Micheal.Mathis@asazlab.com "cn=Micheal.Mathis,ou=UserAccounts,dc=asazlab,dc=com" -fn "Micheal" -ln "Mathis" -disabled no -display "Micheal Mathis" -desc "Uranium Squadron Officer In Charge, Aviation Unit Or Detachment" -office "DevLabs Uranium Squadron" -title "Officer In Charge, Aviation Unit Or Detachment" -company "DevLabs" -PWD "Badpass97915"
                    DSADD user -upn Maxine.James@asazlab.com "cn=Maxine.James,ou=UserAccounts,dc=asazlab,dc=com" -fn "Maxine" -ln "James" -disabled no -display "Maxine James" -desc "Uranium Squadron Chambermaid" -office "DevLabs Uranium Squadron" -title "Chambermaid" -company "DevLabs" -PWD "Badpass28066"
                    DSADD user -upn Susie.Vargas@asazlab.com "cn=Susie.Vargas,ou=UserAccounts,dc=asazlab,dc=com" -fn "Susie" -ln "Vargas" -disabled no -display "Susie Vargas" -desc "Uranium Squadron Roof Truss Builder" -office "DevLabs Uranium Squadron" -title "Roof Truss Builder" -company "DevLabs" -PWD "Badpass63429"
                    DSADD user -upn Gayle.Mullins@asazlab.com "cn=Gayle.Mullins,ou=UserAccounts,dc=asazlab,dc=com" -fn "Gayle" -ln "Mullins" -disabled no -display "Gayle Mullins" -desc "Uranium Squadron Refinery Process Engineer" -office "DevLabs Uranium Squadron" -title "Refinery Process Engineer" -company "DevLabs" -PWD "Badpass65072"
                    DSADD user -upn Clayton.Vega@asazlab.com "cn=Clayton.Vega,ou=UserAccounts,dc=asazlab,dc=com" -fn "Clayton" -ln "Vega" -disabled no -display "Clayton Vega" -desc "Uranium Squadron Podiatric Aide" -office "DevLabs Uranium Squadron" -title "Podiatric Aide" -company "DevLabs" -PWD "Badpass89212"
                    DSADD user -upn Lance.Reed@asazlab.com "cn=Lance.Reed,ou=UserAccounts,dc=asazlab,dc=com" -fn "Lance" -ln "Reed" -disabled no -display "Lance Reed" -desc "Uranium Squadron Certified Respiratory Therapy Technician" -office "DevLabs Uranium Squadron" -title "Certified Respiratory Therapy Technician" -company "DevLabs" -PWD "Badpass73785"
                    DSADD user -upn Jon.Barrett@asazlab.com "cn=Jon.Barrett,ou=UserAccounts,dc=asazlab,dc=com" -fn "Jon" -ln "Barrett" -disabled no -display "Jon Barrett" -desc "Nano Spectral Sagittarius Ballerina" -office "DevLabs Nano Spectral Sagittarius" -title "Ballerina" -company "DevLabs" -PWD "Badpass82151"
                    DSADD user -upn Leigh.Bell@asazlab.com "cn=Leigh.Bell,ou=UserAccounts,dc=asazlab,dc=com" -fn "Leigh" -ln "Bell" -disabled no -display "Leigh Bell" -desc "Nano Spectral Sagittarius Low Altitude Air Defense (Laad) Gunner" -office "DevLabs Nano Spectral Sagittarius" -title "Low Altitude Air Defense (Laad) Gunner" -company "DevLabs" -PWD "Badpass81599"
                    DSADD user -upn Ernestine.Carson@asazlab.com "cn=Ernestine.Carson,ou=UserAccounts,dc=asazlab,dc=com" -fn "Ernestine" -ln "Carson" -disabled no -display "Ernestine Carson" -desc "Nano Spectral Sagittarius Offset Lithographic Press Setter and Set-Up Operator" -office "DevLabs Nano Spectral Sagittarius" -title "Offset Lithographic Press Setter and Set-Up Operator" -company "DevLabs" -PWD "Badpass23341"
                    DSADD user -upn Martha.Maldonado@asazlab.com "cn=Martha.Maldonado,ou=UserAccounts,dc=asazlab,dc=com" -fn "Martha" -ln "Maldonado" -disabled no -display "Martha Maldonado" -desc "Nano Spectral Sagittarius Financial Director" -office "DevLabs Nano Spectral Sagittarius" -title "Financial Director" -company "DevLabs" -PWD "Badpass14969"
                    DSADD user -upn Calvin.Powell@asazlab.com "cn=Calvin.Powell,ou=UserAccounts,dc=asazlab,dc=com" -fn "Calvin" -ln "Powell" -disabled no -display "Calvin Powell" -desc "Nano Spectral Sagittarius Milking Machine Mechanic" -office "DevLabs Nano Spectral Sagittarius" -title "Milking Machine Mechanic" -company "DevLabs" -PWD "Badpass34364"
                    DSADD user -upn Cathy.Schultz@asazlab.com "cn=Cathy.Schultz,ou=UserAccounts,dc=asazlab,dc=com" -fn "Cathy" -ln "Schultz" -disabled no -display "Cathy Schultz" -desc "Nano Spectral Sagittarius County Surveyor" -office "DevLabs Nano Spectral Sagittarius" -title "County Surveyor" -company "DevLabs" -PWD "Badpass53098"
                    DSADD user -upn Phyllis.Washington@asazlab.com "cn=Phyllis.Washington,ou=UserAccounts,dc=asazlab,dc=com" -fn "Phyllis" -ln "Washington" -disabled no -display "Phyllis Washington" -desc "Nano Spectral Sagittarius Oil Pipeline Dispatcher" -office "DevLabs Nano Spectral Sagittarius" -title "Oil Pipeline Dispatcher" -company "DevLabs" -PWD "Badpass75024"
                    DSADD user -upn Homer.Simmons@asazlab.com "cn=Homer.Simmons,ou=UserAccounts,dc=asazlab,dc=com" -fn "Homer" -ln "Simmons" -disabled no -display "Homer Simmons" -desc "Nano Spectral Sagittarius Service Order Clerk" -office "DevLabs Nano Spectral Sagittarius" -title "Service Order Clerk" -company "DevLabs" -PWD "Badpass92861"
                    DSADD user -upn Delores.Wright@asazlab.com "cn=Delores.Wright,ou=UserAccounts,dc=asazlab,dc=com" -fn "Delores" -ln "Wright" -disabled no -display "Delores Wright" -desc "Nano Spectral Sagittarius City Alderman" -office "DevLabs Nano Spectral Sagittarius" -title "City Alderman" -company "DevLabs" -PWD "Badpass68246"
                    DSADD user -upn Amos.Edwards@asazlab.com "cn=Amos.Edwards,ou=UserAccounts,dc=asazlab,dc=com" -fn "Amos" -ln "Edwards" -disabled no -display "Amos Edwards" -desc "Nano Spectral Sagittarius CEO" -office "DevLabs Nano Spectral Sagittarius" -title "CEO" -company "DevLabs" -PWD "Badpass4921"
                    DSADD user -upn Roy.Cross@asazlab.com "cn=Roy.Cross,ou=UserAccounts,dc=asazlab,dc=com" -fn "Roy" -ln "Cross" -disabled no -display "Roy Cross" -desc "Nano Spectral Sagittarius Chief Executive Officer" -office "DevLabs Nano Spectral Sagittarius" -title "Chief Executive Officer" -company "DevLabs" -PWD "Badpass13822"
                    DSADD user -upn Alberta.Armstrong@asazlab.com "cn=Alberta.Armstrong,ou=UserAccounts,dc=asazlab,dc=com" -fn "Alberta" -ln "Armstrong" -disabled no -display "Alberta Armstrong" -desc "Nano Spectral Sagittarius Chief Operating Officer" -office "DevLabs Nano Spectral Sagittarius" -title "Chief Operating Officer" -company "DevLabs" -PWD "Badpass78144"
                    DSADD user -upn Rochelle.Hughes@asazlab.com "cn=Rochelle.Hughes,ou=UserAccounts,dc=asazlab,dc=com" -fn "Rochelle" -ln "Hughes" -disabled no -display "Rochelle Hughes" -desc "Nano Spectral Sagittarius Commissioner of Internal Revenue" -office "DevLabs Nano Spectral Sagittarius" -title "Commissioner of Internal Revenue" -company "DevLabs" -PWD "Badpass16043"
                    DSADD user -upn Irene.Houston@asazlab.com "cn=Irene.Houston,ou=UserAccounts,dc=asazlab,dc=com" -fn "Irene" -ln "Houston" -disabled no -display "Irene Houston" -desc "Nano Spectral Sagittarius COO" -office "DevLabs Nano Spectral Sagittarius" -title "COO" -company "DevLabs" -PWD "Badpass51156"
                    DSADD user -upn Byron.Lawrence@asazlab.com "cn=Byron.Lawrence,ou=UserAccounts,dc=asazlab,dc=com" -fn "Byron" -ln "Lawrence" -disabled no -display "Byron Lawrence" -desc "Nano Spectral Sagittarius County Commissioner" -office "DevLabs Nano Spectral Sagittarius" -title "County Commissioner" -company "DevLabs" -PWD "Badpass74862"
                    DSADD user -upn Marion.Gonzalez@asazlab.com "cn=Marion.Gonzalez,ou=UserAccounts,dc=asazlab,dc=com" -fn "Marion" -ln "Gonzalez" -disabled no -display "Marion Gonzalez" -desc "Nano Spectral Sagittarius Government Service Executive" -office "DevLabs Nano Spectral Sagittarius" -title "Government Service Executive" -company "DevLabs" -PWD "Badpass62004"
                    DSADD user -upn Gerald.Wade@asazlab.com "cn=Gerald.Wade,ou=UserAccounts,dc=asazlab,dc=com" -fn "Gerald" -ln "Wade" -disabled no -display "Gerald Wade" -desc "Nano Spectral Sagittarius City Alderman" -office "DevLabs Nano Spectral Sagittarius" -title "City Alderman" -company "DevLabs" -PWD "Badpass35101"
                    DSADD user -upn Donna.Garner@asazlab.com "cn=Donna.Garner,ou=UserAccounts,dc=asazlab,dc=com" -fn "Donna" -ln "Garner" -disabled no -display "Donna Garner" -desc "Compu Matrix M City Council Member" -office "DevLabs Compu Matrix M" -title "City Council Member" -company "DevLabs" -PWD "Badpass63050"
                }
                catch 
                {
                    Write-Host "creating Accounts"
                }


                Write-Host "Creating FS objects"
                try 
                {
                    DSADD user -upn fileadmin@asazlab.com "cn=fileadmin,ou=ServiceAdmins,dc=asazlab,dc=com" -fn "file" -ln "admin" -disabled no -display "FileServiceAdmin"  -office "Administration"  -PWD "Adm1nP@55!"
                    setspn -a srv01/fileadmin.asazlab.com:1433 asazlab.com\fileadmin
                    New-ADGroup "sec_filesadmins" -Path "OU=SG_FileShares,OU=SecurityGroups,DC=asazlab,DC=com" -GroupCategory Security -GroupScope DomainLocal -PassThru –Verbose
                    New-ADGroup "sec_files_Accounting-rw" -Path "OU=SG_FileShares,OU=SecurityGroups,DC=asazlab,DC=com" -GroupCategory Security -GroupScope DomainLocal -PassThru –Verbose
                    New-ADGroup "sec_files_HR-rw" -Path "OU=SG_FileShares,OU=SecurityGroups,DC=asazlab,DC=com" -GroupCategory Security -GroupScope DomainLocal -PassThru –Verbose
                    New-ADGroup "sec_files_ExecutiveOffice-rw" -Path "OU=SG_FileShares,OU=SecurityGroups,DC=asazlab,DC=com" -GroupCategory Security -GroupScope DomainLocal -PassThru –Verbose
                    New-ADGroup "sec_files_IT-rw" -Path "OU=SG_FileShares,OU=SecurityGroups,DC=asazlab,DC=com" -GroupCategory Security -GroupScope DomainLocal -PassThru –Verbose
                    New-ADGroup "sec_files_Security-rw" -Path "OU=SG_FileShares,OU=SecurityGroups,DC=asazlab,DC=com" -GroupCategory Security -GroupScope DomainLocal -PassThru –Verbose
                    New-ADGroup "sec_files_Accounting-ro" -Path "OU=SG_FileShares,OU=SecurityGroups,DC=asazlab,DC=com" -GroupCategory Security -GroupScope DomainLocal -PassThru –Verbose
                    New-ADGroup "sec_files_HR-ro" -Path "OU=SG_FileShares,OU=SecurityGroups,DC=asazlab,DC=com" -GroupCategory Security -GroupScope DomainLocal -PassThru –Verbose
                    New-ADGroup "sec_files_ExecutiveOffice-ro" -Path "OU=SG_FileShares,OU=SecurityGroups,DC=asazlab,DC=com" -GroupCategory Security -GroupScope DomainLocal -PassThru –Verbose
                    New-ADGroup "sec_files_IT-ro" -Path "OU=SG_FileShares,OU=SecurityGroups,DC=asazlab,DC=com" -GroupCategory Security -GroupScope DomainLocal -PassThru –Verbose
                    New-ADGroup "sec_files_Security-ro" -Path "OU=SG_FileShares,OU=SecurityGroups,DC=asazlab,DC=com" -GroupCategory Security -GroupScope DomainLocal -PassThru –Verbose
                    New-ADGroup "sec_files_Accounting-d" -Path "OU=SG_FileShares,OU=SecurityGroups,DC=asazlab,DC=com" -GroupCategory Security -GroupScope DomainLocal -PassThru –Verbose
                    New-ADGroup "sec_files_HR-d" -Path "OU=SG_FileShares,OU=SecurityGroups,DC=asazlab,DC=com" -GroupCategory Security -GroupScope DomainLocal -PassThru –Verbose
                    New-ADGroup "sec_files_ExecutiveOffice-d" -Path "OU=SG_FileShares,OU=SecurityGroups,DC=asazlab,DC=com" -GroupCategory Security -GroupScope DomainLocal -PassThru –Verbose
                    New-ADGroup "sec_files_IT-d" -Path "OU=SG_FileShares,OU=SecurityGroups,DC=asazlab,DC=com" -GroupCategory Security -GroupScope DomainLocal -PassThru –Verbose
                    New-ADGroup "sec_files_Security-d" -Path "OU=SG_FileShares,OU=SecurityGroups,DC=asazlab,DC=com" -GroupCategory Security -GroupScope DomainLocal -PassThru –Verbose
                    ADD-ADGroupMember "sec_filesadmins" –members "fileadmin"
                    ADD-ADGroupMember "sec_filesadmins" –members "Domain Admins"
                    ADD-ADGroupMember "sec_files_Accounting-ro" –members "Domain Users"
                    ADD-ADGroupMember "sec_files_HR-ro" –members "Domain Users"
                    ADD-ADGroupMember "sec_files_ExecutiveOffice-ro" –members "Domain Users"
                    ADD-ADGroupMember "sec_files_IT-ro" –members "Domain Users"
                    ADD-ADGroupMember "sec_files_Security-ro" –members "Domain Users"
                }
                catch
                {
                    Write-Host "Failed creating FS objects"
                }


                Write-Host "add user accounts DSC complete "

            }

            
            GetScript =  
            {
                # This block must return a hashtable. The hashtable must only contain one key Result and the value must be of type String.
                return @{ "Result" = "false" }
            }
            TestScript = 
            {
                # If it returns $false, the SetScript block will run. If it returns $true, the SetScript block will not run.
                return $false
            }
        }
    }
}



function Get-NetBIOSName {
    [OutputType([string])]
    param(
        [string]$DomainFQDN
    )

    if ($DomainFQDN.Contains('.')) {
        $length = $DomainFQDN.IndexOf('.')
        if ( $length -ge 16) {
            $length = 15
        }
        return $DomainFQDN.Substring(0, $length)
    }
    else {
        if ($DomainFQDN.Length -gt 15) {
            return $DomainFQDN.Substring(0, 15)
        }
        else {
            return $DomainFQDN
        }
    }
}